#theme: jekyll-theme-cayman
remote-theme: jekyll-mdl

title: Android курс в Технополисе 2019

# Layout settings
header_type: drawer  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Cool Option 1
    link: www.myawesomelink.com
  option2:
    name: Cool Option 2
    link: www.myawesomelink.com
  option3:
    name: Cool Option 3
    link: www.myawesomelink.com

disqus: true
disqus_shortname: 'gdgmanagua'

# Build settings
markdown: kramdown
